---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels:
    app: "k8s"
  name: "helloworldservice"
spec:
  ports:
  - port: 9095
    protocol: "TCP"
    targetPort: 9095
  selector:
    app: "k8s"
  type: "NodePort"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations: {}
  labels:
    app: "k8s"
  name: "helloworldservice"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "k8s"
  template:
    metadata:
      annotations: {}
      labels:
        app: "k8s"
    spec:
      containers:
      - image: "harshal0812/helloworldservice"
        imagePullPolicy: "IfNotPresent"
        name: "helloworldservice"
        ports:
        - containerPort: 9095
          protocol: "TCP"
      nodeSelector: {}
